language: go

go:
  - "1.11.2"

before_install:
  - go get -v github.com/stretchr/testify/require

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_KEY
  file:
  - fstahs.linux.amd64
  on:
    tags: true
    condition: $LATEST = true
